### ISSUE TITLE
Douple list in toolbars

### ISSUE THREAD

**Issue by nh0cmagic** [SpinVFX/spin_nuke_gizmos#1]
Hi! I know that my question is not too good. When i installed them, i saw double list on toolbar. So can you guide me how to fix it ?

My nuke is running on Windows 10.

Thanks you so much and merry christmas.

![screenshot 160](https://user-images.githubusercontent.com/45961843/50413816-2e5a9f00-0844-11e9-98dc-d0842bf97e0d.jpg)

**Comment by herronelou** [comment]
Hey thanks for the comment.
Made the code on Linux, probably a path issue with Windows.
I'll take a look at it asap.

**Comment by herronelou** [comment]
Hey, check release 1.1.0, it should be all fixed

**Comment by nh0cmagic** [comment]
Woa. It's working perfect. Thank you for working on christmas day.

![screenshot 172](https://user-images.githubusercontent.com/45961843/50432588-6544b980-0905-11e9-9488-b77a08aaec9a.png)
